### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by jasonw4331** [jasonwynn10/MiningDimension#1]
- [ ] Complete Generator
  - [ ] Add Cave Populators
  - [ ] Add Other Populators
- [x] Register new block for portals
- [x] Register new items for portals
- [ ] Create Texture/Resource Pack for custom blocks and items
- [ ] Make dimension work as actual dimension rather than using multiple levels

**Comment by Tgstream** [comment]
Where is the download button
